#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask ${UMASK}

if [ "${NASTOOL_UI_MODE:-legacy}" = "react" ]; then
    export NASTOOL_LEGACY_PORT="${NASTOOL_LEGACY_PORT:-3002}"
    NT_PORT="${NASTOOL_LEGACY_PORT}"
elif [ -f ${NASTOOL_CONFIG} ]; then
    NT_PORT=$(yq '.app.web_port' "${NASTOOL_CONFIG}")
else
    NT_PORT=3000
fi
if ! [[ "${NT_PORT}" =~ ^[0-9]+$ ]]; then
    if [ "${NASTOOL_UI_MODE:-legacy}" = "react" ]; then
        NT_PORT=3002
        export NASTOOL_LEGACY_PORT="${NT_PORT}"
    else
        NT_PORT=3000
    fi
fi

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost ${NT_PORT}" \
    cd ${WORKDIR} s6-setuidgid nt python3 run.py
